sudo: required

language: generic

services:
  - docker

env:
  global:
    - PROJECT_NAME=upx
    - DOCKER_IMAGE_NAME=$DOCKER_USER/$PROJECT_NAME
    - GIT_COMMIT_HASH=0430e79

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

jobs:
  include:
    - stage: build docker image
      script:
        - |
          docker build \
          --build-arg UPX_COMMIT_HASH=${GIT_COMMIT_HASH} \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          -t ${DOCKER_IMAGE_NAME}:test \
          .
        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
        - docker push ${DOCKER_IMAGE_NAME}:test
    - stage: test
      script: DOCKER_IMAGE_VERSION_NAME=${DOCKER_IMAGE_NAME}:test ./tests/golang.sh
    - stage: test
      script: DOCKER_IMAGE_VERSION_NAME=${DOCKER_IMAGE_NAME}:test ./tests/rust.sh

after_success:
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
  - docker tag ${DOCKER_IMAGE_NAME}:test ${DOCKER_IMAGE_NAME}:dev-${GIT_COMMIT_HASH}
  - docker push ${DOCKER_IMAGE_NAME}:dev-${GIT_COMMIT_HASH}
