sudo: required

language: generic

services:
  - docker

env:
  global:
    - DOCKER_IMAGE_NAME=upx
    - DOCKER_REPO=$DOCKER_USER/$DOCKER_IMAGE_NAME

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  - docker build -t $DOCKER_IMAGE_NAME-test .

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker tag $DOCKER_IMAGE_NAME-test $DOCKER_REPO:latest
  - docker push $DOCKER_REPO:latest
